// Store type and product recommendations
import { StoreType } from '@prisma/client';

export const STORE_TYPES = [
	{ id: 'EATERY', label: 'Eatery', icon: '🍔' },
	{ id: 'COSMETICS', label: 'Cosmetics', icon: '💄' },
	{ id: 'GROCERY', label: 'Grocery', icon: '🥬' },
	{ id: 'PROVISIONS', label: 'Provisions/General Store', icon: '🛍️' },
	{ id: 'PHARMACY', label: 'Pharmacy', icon: '💊' },
	{ id: 'FASHION', label: 'Fashion/Clothing', icon: '👕' },
	{ id: 'ELECTRONICS', label: 'Electronics', icon: '📱' },
	{ id: 'BAKERY', label: 'Bakery', icon: '🥐' },
	{ id: 'BOOKSTORE', label: 'Bookstore', icon: '📚' },
	{ id: 'STATIONERY', label: 'Stationery', icon: '✏️' },
	{ id: 'BEVERAGES', label: 'Beverages', icon: '🥤' },
	{ id: 'GARDEN', label: 'Garden', icon: '🌿' },
	{ id: 'HOME', label: 'Home & Living', icon: '🏠' },
	{ id: 'TOYS', label: 'Toys', icon: '🧸' },
];

export const PRODUCTS_BY_STORE_TYPE: Record<string, any[]> = {
	EATERY: [
		{
			name: 'Coca-Cola 50cl',
			brand: 'Coca-Cola',
			category: 'Beverages',
			costPrice: 200,
			sellingPrice: 250,
			unitName: 'Bottle',
			image:
				'https://images.unsplash.com/photo-1554866585-d7ab9e3e20ad?w=400&h=400&fit=crop',
		},
		{
			name: 'Pepsi 50cl',
			brand: 'Pepsi',
			category: 'Beverages',
			costPrice: 200,
			sellingPrice: 250,
			unitName: 'Bottle',
			image:
				'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400&h=400&fit=crop',
		},
		{
			name: 'Fanta 50cl',
			brand: 'Fanta',
			category: 'Beverages',
			costPrice: 200,
			sellingPrice: 250,
			unitName: 'Bottle',
			image:
				'https://images.unsplash.com/photo-1530714955267-5e56a2ac8199?w=400&h=400&fit=crop',
		},
		{
			name: 'Sprite 50cl',
			brand: 'Sprite',
			category: 'Beverages',
			costPrice: 200,
			sellingPrice: 250,
			unitName: 'Bottle',
			image:
				'https://images.unsplash.com/photo-1559042615-cd4628902d4a?w=400&h=400&fit=crop',
		},
		{
			name: 'Bread',
			brand: 'Local',
			category: 'Bakery',
			costPrice: 500,
			sellingPrice: 700,
			unitName: 'Loaf',
			image:
				'https://images.unsplash.com/photo-1550507163e22-b55c37d0c1f1?w=400&h=400&fit=crop',
		},
		{
			name: 'Eggs',
			brand: 'Local',
			category: 'Groceries',
			costPrice: 30,
			sellingPrice: 40,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=400&fit=crop',
		},
		{
			name: 'Chicken',
			brand: 'Local',
			category: 'Meat',
			costPrice: 2500,
			sellingPrice: 3000,
			unitName: 'Kg',
			image:
				'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=400&fit=crop',
		},
		{
			name: 'Rice',
			brand: 'Local',
			category: 'Grains',
			costPrice: 8000,
			sellingPrice: 10000,
			unitName: 'Kg',
			image:
				'https://images.unsplash.com/photo-1586080876-1e53bb4efb02?w=400&h=400&fit=crop',
		},
	],
	COSMETICS: [
		{
			name: 'Body Lotion',
			brand: 'Ponds',
			category: 'Skincare',
			costPrice: 1500,
			sellingPrice: 2000,
			unitName: 'Bottle',
			image:
				'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
		},
		{
			name: 'Face Cream',
			brand: 'Olay',
			category: 'Skincare',
			costPrice: 2000,
			sellingPrice: 3000,
			unitName: 'Jar',
			image:
				'https://images.unsplash.com/photo-1556209174-0ea4483e3910?w=400&h=400&fit=crop',
		},
		{
			name: 'Lipstick',
			brand: 'Revlon',
			category: 'Lipstick',
			costPrice: 2500,
			sellingPrice: 4000,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1545016681-4d89f7d37298?w=400&h=400&fit=crop',
		},
		{
			name: 'Mascara',
			brand: 'Maybelline',
			category: 'Makeup',
			costPrice: 1500,
			sellingPrice: 2500,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1560373129-26b10f17bb21?w=400&h=400&fit=crop',
		},
		{
			name: 'Foundation',
			brand: 'MAC',
			category: 'Makeup',
			costPrice: 3000,
			sellingPrice: 5000,
			unitName: 'Bottle',
			image:
				'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=400&fit=crop',
		},
		{
			name: 'Shampoo',
			brand: 'Clear',
			category: 'Hair Care',
			costPrice: 800,
			sellingPrice: 1200,
			unitName: 'Bottle',
			image:
				'https://images.unsplash.com/photo-1535237099417-d7b28b1f6a3c?w=400&h=400&fit=crop',
		},
		{
			name: 'Conditioner',
			brand: 'Clear',
			category: 'Hair Care',
			costPrice: 800,
			sellingPrice: 1200,
			unitName: 'Bottle',
			image:
				'https://images.unsplash.com/photo-1541197601327-42f8f5765d3b?w=400&h=400&fit=crop',
		},
		{
			name: 'Perfume',
			brand: 'Prada',
			category: 'Fragrance',
			costPrice: 5000,
			sellingPrice: 8000,
			unitName: 'Bottle',
			image:
				'https://images.unsplash.com/photo-1596040242658-7a4cb5b7e5e3?w=400&h=400&fit=crop',
		},
	],
	GROCERY: [
		{
			name: 'Rice',
			brand: 'Local',
			category: 'Grains',
			costPrice: 8000,
			sellingPrice: 10000,
			unitName: 'Kg',
		},
		{
			name: 'Beans',
			brand: 'Local',
			category: 'Legumes',
			costPrice: 6000,
			sellingPrice: 8000,
			unitName: 'Kg',
		},
		{
			name: 'Flour',
			brand: 'Golden Penny',
			category: 'Flour',
			costPrice: 2000,
			sellingPrice: 2500,
			unitName: 'Kg',
		},
		{
			name: 'Oil',
			brand: 'Vegetable',
			category: 'Cooking Oil',
			costPrice: 5000,
			sellingPrice: 6500,
			unitName: 'Liter',
		},
		{
			name: 'Tomato Paste',
			brand: 'Dangote',
			category: 'Condiments',
			costPrice: 400,
			sellingPrice: 600,
			unitName: 'Tin',
		},
		{
			name: 'Sugar',
			brand: 'Golden Sugar',
			category: 'Sweetener',
			costPrice: 200,
			sellingPrice: 300,
			unitName: 'Kg',
		},
		{
			name: 'Salt',
			brand: 'Local',
			category: 'Seasoning',
			costPrice: 300,
			sellingPrice: 500,
			unitName: 'Kg',
		},
		{
			name: 'Seasoning Cube',
			brand: 'Maggi',
			category: 'Seasonings',
			costPrice: 100,
			sellingPrice: 150,
			unitName: 'Cube',
		},
	],
	PROVISIONS: [
		{
			name: 'Milk',
			brand: 'Peak',
			category: 'Dairy',
			costPrice: 1000,
			sellingPrice: 1300,
			unitName: 'Tin',
		},
		{
			name: 'Butter',
			brand: 'Blue Band',
			category: 'Dairy',
			costPrice: 800,
			sellingPrice: 1100,
			unitName: 'Tin',
		},
		{
			name: 'Eggs',
			brand: 'Local',
			category: 'Groceries',
			costPrice: 30,
			sellingPrice: 40,
			unitName: 'Piece',
		},
		{
			name: 'Bread',
			brand: 'Local',
			category: 'Bakery',
			costPrice: 500,
			sellingPrice: 700,
			unitName: 'Loaf',
		},
		{
			name: 'Biscuits',
			brand: 'digestive',
			category: 'Snacks',
			costPrice: 300,
			sellingPrice: 500,
			unitName: 'Pack',
		},
		{
			name: 'Noodles',
			brand: 'Indomie',
			category: 'Noodles',
			costPrice: 50,
			sellingPrice: 100,
			unitName: 'Pack',
		},
		{
			name: 'Canned Fish',
			brand: 'Titus',
			category: 'Canned Food',
			costPrice: 500,
			sellingPrice: 700,
			unitName: 'Tin',
		},
		{
			name: 'Juice',
			brand: 'Fanta',
			category: 'Beverages',
			costPrice: 200,
			sellingPrice: 300,
			unitName: 'Sachet',
		},
	],
	PHARMACY: [
		{
			name: 'Paracetamol',
			brand: 'Tylenol',
			category: 'Pain Relief',
			costPrice: 10,
			sellingPrice: 20,
			unitName: 'Tablet',
		},
		{
			name: 'Antibiotic',
			brand: 'Amoxicillin',
			category: 'Antibiotics',
			costPrice: 50,
			sellingPrice: 100,
			unitName: 'Tablet',
		},
		{
			name: 'Cough Syrup',
			brand: 'Benylin',
			category: 'Cough',
			costPrice: 300,
			sellingPrice: 500,
			unitName: 'Bottle',
		},
		{
			name: 'Antiseptic',
			brand: 'Dettol',
			category: 'Antiseptic',
			costPrice: 1000,
			sellingPrice: 1500,
			unitName: 'Bottle',
		},
		{
			name: 'Bandages',
			brand: 'Johnson & Johnson',
			category: 'First Aid',
			costPrice: 100,
			sellingPrice: 200,
			unitName: 'Pack',
		},
		{
			name: 'Vitamins',
			brand: 'Pharmaton',
			category: 'Vitamins',
			costPrice: 500,
			sellingPrice: 800,
			unitName: 'Bottle',
		},
		{
			name: 'Condoms',
			brand: 'Durex',
			category: 'Contraceptive',
			costPrice: 200,
			sellingPrice: 400,
			unitName: 'Pack',
		},
	],
	FASHION: [
		{
			name: 'T-Shirt',
			brand: 'Generic',
			category: 'Tops',
			costPrice: 1500,
			sellingPrice: 3000,
			unitName: 'Piece',
		},
		{
			name: 'Jeans',
			brand: 'Generic',
			category: 'Bottoms',
			costPrice: 5000,
			sellingPrice: 10000,
			unitName: 'Piece',
		},
		{
			name: 'Dress',
			brand: 'Generic',
			category: 'Dresses',
			costPrice: 3000,
			sellingPrice: 6000,
			unitName: 'Piece',
		},
		{
			name: 'Shoes',
			brand: 'Generic',
			category: 'Footwear',
			costPrice: 3000,
			sellingPrice: 6000,
			unitName: 'Pair',
		},
		{
			name: 'Hat',
			brand: 'Generic',
			category: 'Accessories',
			costPrice: 800,
			sellingPrice: 1500,
			unitName: 'Piece',
		},
		{
			name: 'Bag',
			brand: 'Generic',
			category: 'Bags',
			costPrice: 2000,
			sellingPrice: 4000,
			unitName: 'Piece',
		},
		{
			name: 'Belt',
			brand: 'Generic',
			category: 'Accessories',
			costPrice: 1000,
			sellingPrice: 2000,
			unitName: 'Piece',
		},
	],
	ELECTRONICS: [
		{
			name: 'Phone Charger',
			brand: 'Generic',
			category: 'Accessories',
			costPrice: 1000,
			sellingPrice: 2000,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1619983081854-430f63602796?w=400&h=400&fit=crop',
		},
		{
			name: 'USB Cable',
			brand: 'Generic',
			category: 'Accessories',
			costPrice: 300,
			sellingPrice: 600,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=400&h=400&fit=crop',
		},
		{
			name: 'Headphones',
			brand: 'Generic',
			category: 'Audio',
			costPrice: 2000,
			sellingPrice: 4000,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
		},
		{
			name: 'Phone Case',
			brand: 'Generic',
			category: 'Accessories',
			costPrice: 500,
			sellingPrice: 1000,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=400&fit=crop',
		},
		{
			name: 'Screen Protector',
			brand: 'Generic',
			category: 'Accessories',
			costPrice: 200,
			sellingPrice: 500,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=400&h=400&fit=crop',
		},
		{
			name: 'Power Bank',
			brand: 'Generic',
			category: 'Power',
			costPrice: 3000,
			sellingPrice: 5000,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop',
		},
		{
			name: 'Memory Card',
			brand: 'Generic',
			category: 'Storage',
			costPrice: 1500,
			sellingPrice: 3000,
			unitName: 'Piece',
			image:
				'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400&h=400&fit=crop',
		},
	],
	BAKERY: [
		{
			name: 'Loaf Bread',
			brand: 'Local',
			category: 'Bakery',
			costPrice: 400,
			sellingPrice: 600,
			unitName: 'Loaf',
			keywords: ['bread', 'bakery', 'loaf'],
		},
		{
			name: 'Cake Slice',
			brand: 'Local',
			category: 'Bakery',
			costPrice: 800,
			sellingPrice: 1200,
			unitName: 'Slice',
			keywords: ['cake', 'dessert'],
		},
		{
			name: 'Croissant',
			brand: 'Local',
			category: 'Bakery',
			costPrice: 300,
			sellingPrice: 500,
			unitName: 'Piece',
			keywords: ['croissant', 'pastry'],
		},
	],
	BOOKSTORE: [
		{
			name: 'Notebook A5',
			brand: 'Generic',
			category: 'Notebooks',
			costPrice: 200,
			sellingPrice: 400,
			unitName: 'Piece',
			keywords: ['notebook', 'notes', 'paper'],
		},
		{
			name: 'Reading Book',
			brand: 'Generic',
			category: 'Books',
			costPrice: 700,
			sellingPrice: 1200,
			unitName: 'Piece',
			keywords: ['book', 'reading'],
		},
		{
			name: 'Children Storybook',
			brand: 'Generic',
			category: 'Books',
			costPrice: 500,
			sellingPrice: 900,
			unitName: 'Piece',
			keywords: ['children', 'storybook'],
		},
	],
	STATIONERY: [
		{
			name: 'Ballpoint Pen',
			brand: 'BIC',
			category: 'Writing',
			costPrice: 50,
			sellingPrice: 120,
			unitName: 'Piece',
			keywords: ['pen', 'writing'],
		},
		{
			name: 'Pencil',
			brand: 'Generic',
			category: 'Writing',
			costPrice: 30,
			sellingPrice: 80,
			unitName: 'Piece',
			keywords: ['pencil', 'writing'],
		},
		{
			name: 'Eraser',
			brand: 'Generic',
			category: 'Accessories',
			costPrice: 20,
			sellingPrice: 50,
			unitName: 'Piece',
			keywords: ['eraser'],
		},
	],
	BEVERAGES: [
		{
			name: 'Mineral Water 1L',
			brand: 'Eva',
			category: 'Beverages',
			costPrice: 100,
			sellingPrice: 150,
			unitName: 'Bottle',
			keywords: ['water', 'beverage'],
		},
		{
			name: 'Energy Drink 330ml',
			brand: 'Red Bull',
			category: 'Beverages',
			costPrice: 400,
			sellingPrice: 700,
			unitName: 'Can',
			keywords: ['energy', 'drink'],
		},
	],
	GARDEN: [
		{
			name: 'Plant Fertilizer 1kg',
			brand: 'GrowMore',
			category: 'Garden',
			costPrice: 1500,
			sellingPrice: 2000,
			unitName: 'Bag',
			keywords: ['fertilizer', 'garden'],
		},
		{
			name: 'Garden Shears',
			brand: 'Generic',
			category: 'Tools',
			costPrice: 1200,
			sellingPrice: 2000,
			unitName: 'Piece',
			keywords: ['shears', 'garden'],
		},
	],
	HOME: [
		{
			name: 'Ceramic Plate',
			brand: 'Homeware',
			category: 'Kitchen',
			costPrice: 800,
			sellingPrice: 1500,
			unitName: 'Piece',
			keywords: ['plate', 'kitchen'],
		},
		{
			name: 'Cushion',
			brand: 'Homeware',
			category: 'Decor',
			costPrice: 1000,
			sellingPrice: 1800,
			unitName: 'Piece',
			keywords: ['cushion', 'decor'],
		},
	],
	TOYS: [
		{
			name: 'Teddy Bear',
			brand: 'ToyCo',
			category: 'Plush',
			costPrice: 1200,
			sellingPrice: 2200,
			unitName: 'Piece',
			keywords: ['teddy', 'toy'],
		},
		{
			name: 'Building Blocks',
			brand: 'ToyCo',
			category: 'Blocks',
			costPrice: 1500,
			sellingPrice: 3000,
			unitName: 'Set',
			keywords: ['blocks', 'toy'],
		},
	],
};
